In [1]:
import pandas as pd
original_data_dir = '../original_data/'
clean_data_dir = '../clean_data/'

In [2]:
starbucks = pd.read_csv(original_data_dir + 'starbucks.csv')
gdp = pd.read_csv(original_data_dir + 'gdp.csv')
shanghai = pd.read_csv(original_data_dir + 'shanghai_2019.csv')
population = pd.read_csv(original_data_dir + 'population.csv')

# Shanghai

In [3]:
districts = [
    "Pudong New Area",
    "Huangpu",
    "Xuhui",
    "Changning",
    "Jing'an",
    "Putuo",
    "Hongkou",
    "Yangpu",
    "Minhang",
    "Baoshan",
    "Jiading",
    "Jinshan",
    "Songjiang",
    "Qingpu",
    "Fengxian",
    "Chongming"
]

In [4]:
shanghai

      地区  行政区划面积（平方公里）  年末常住人口（万人）  其中外来人口  人口密度（人/平方公里）
0   浦东新区       1210.41      556.70  234.22          4599
1    黄浦区         20.46       65.08   17.83         31808
2    徐汇区         54.76      109.46   27.45         19989
3    长宁区         38.30       69.36   17.96         18110
4    静安区         36.88      105.77   26.83         28680
5    普陀区         54.83      127.58   34.03         23268
6    虹口区         23.48       79.40   15.46         33816
7    杨浦区         60.73      130.49   27.63         21487
8    闵行区        370.75      254.93  125.14          6876
9    宝山区        270.99      204.43   83.78          7544
10   嘉定区        464.20      159.60   90.48          3438
11   金山区        586.05       80.70   27.32          1377
12   松江区        605.64      177.19  106.31          2926
13   青浦区        670.14      123.31   71.43          1840
14   奉贤区        687.39      115.78   57.72          1684
15   崇明区       1185.49       68.36   14.12           577

In [5]:
shanghai_en = shanghai.rename(columns={'地区': 'District',
                                       '行政区划面积（平方公里）': 'Area',
                                       '年末常住人口（万人）': 'Population',
                                       '人口密度（人/平方公里）': 'Density'})
shanghai_en = shanghai_en.drop('其中外来人口', axis=1)
shanghai_en['District'] = districts
shanghai_en

           District     Area  Population  Density
0   Pudong New Area  1210.41      556.70     4599
1           Huangpu    20.46       65.08    31808
2             Xuhui    54.76      109.46    19989
3         Changning    38.30       69.36    18110
4           Jing'an    36.88      105.77    28680
5             Putuo    54.83      127.58    23268
6           Hongkou    23.48       79.40    33816
7            Yangpu    60.73      130.49    21487
8           Minhang   370.75      254.93     6876
9           Baoshan   270.99      204.43     7544
10          Jiading   464.20      159.60     3438
11          Jinshan   586.05       80.70     1377
12        Songjiang   605.64      177.19     2926
13           Qingpu   670.14      123.31     1840
14         Fengxian   687.39      115.78     1684
15        Chongming  1185.49       68.36      577

In [8]:
shanghai_en.to_csv(clean_data_dir + 'shanghai_2019_en.csv', index=False)

# Population & GDP

In [3]:
population

          Province  Population
0          Beijing    21893095
1          Tianjin    13866009
2            Hebei    74610235
3           Shanxi    34915616
4   Inner Mongolia    24049155
5         Liaoning    42591407
6            Jilin    24073453
7     Heilongjiang    31850088
8         Shanghai    24870895
9          Jiangsu    84748016
10        Zhejiang    64567588
11           Anhui    61027171
12          Fujian    41540086
13         Jiangxi    45188635
14        Shandong   101527453
15           Henan    99365519
16           Hubei    57752557
17           Hunan    66444864
18       Guangdong   126012510
19         Guangxi    50126804
20          Hainan    10081232
21       Chongqing    32054159
22         Sichuan    83674866
23         Guizhou    38562148
24          Yunnan    47209277
25           Tibet     3648100
26         Shaanxi    39528999
27           Gansu    25019831
28         Qinghai     5923957
29         Ningxia     7202654
30        Xinjiang    25852345
31      Servicemen     2000000

In [10]:
gdp

,Year,Beijing,Tianjin,Hebei,Shanxi,Inner Mongolia,Liaoning,Jilin,Heilongjiang,Shanghai,...,Chongqing,Sichuan,Guizhou,Yunnan,Tibet,Shaanxi,Gansu,Qinghai,Ningxia,Xinjiang
0,2020,36102.6,14083.7,36206.9,17651.9,17359.8,25115.0,12311.3,13698.5,38700.6,...,25002.8,48598.8,17826.6,24521.9,1902.7,26181.9,9016.7,3005.9,3920.6,13797.6
1,2019,35445.1,14055.5,34978.6,16961.6,17212.5,24855.3,11726.8,13544.4,37987.6,...,23605.8,46363.8,16769.3,23223.8,1697.8,25793.2,8718.3,2941.1,3748.5,13597.1
2,2018,33106.0,13362.9,32494.6,15958.1,16140.8,23510.5,11253.8,12846.5,36011.8,...,21588.8,42902.1,15353.2,20880.6,1548.4,23941.9,8104.1,2748.0,3510.2,12809.4
3,2017,29883.0,12450.6,30640.8,14484.3,14898.1,21693.0,10922.0,12313.0,32925.0,...,20066.3,37905.1,13605.4,18486.0,1349.0,21473.5,7336.7,2465.1,3200.3,11159.9
4,2016,27041.2,11477.2,28474.1,11946.4,13789.3,20392.5,10427.0,11895.0,29887.0,...,18023.0,33138.5,11792.4,16369.0,1173.0,19045.8,6907.9,2258.2,2781.4,9630.8
5,2015,24779.1,10879.5,26398.4,11836.4,12949.0,20210.3,10018.0,11690.0,26887.0,...,16040.5,30342.0,10541.0,14960.0,1043.0,17898.8,6556.6,2011.0,2579.4,9306.9
6,2014,22926.0,10640.6,25208.9,12094.7,12158.2,20025.7,9966.5,12170.8,25269.8,...,14623.8,28891.3,9173.1,14041.7,939.7,17402.5,6518.4,1847.7,2473.9,9264.5
7,2013,21134.6,9945.4,24259.6,11987.2,11392.4,19208.8,9427.9,11849.1,23204.1,...,13027.6,26518.0,7973.1,12825.5,828.2,15905.4,6014.5,1713.3,2327.7,8392.6
8,2012,19024.7,9043.0,23077.5,11683.1,10470.1,17848.6,8678.0,11015.8,21305.6,...,11595.4,23922.4,6742.2,11097.4,710.2,14142.4,5393.1,1528.5,2131.0,7411.8
9,2011,17188.8,8112.5,21384.7,10894.4,9458.1,16354.9,7734.6,9935.0,20009.7,...,10161.2,21050.9,5615.6,9523.1,611.5,12175.1,4816.9,1370.4,1931.8,6532.0
10,2010,14964.0,6830.8,18003.6,8903.9,8199.9,13896.3,6410.5,8308.3,17915.4,...,8065.3,17224.8,4519.0,7735.3,512.9,9845.2,3943.7,1144.2,1571.7,5360.2
11,2009,12900.9,5709.6,15306.9,7147.6,7104.2,12815.7,5434.8,7218.9,15742.4,...,6651.2,14190.6,3856.7,6574.4,445.7,7997.8,3268.3,939.7,1266.7,4237.0
12,2008,11813.1,5182.4,14200.1,7223.0,6242.4,12137.7,4834.7,7134.2,14536.9,...,5899.5,12756.2,3504.5,6016.6,398.2,7177.8,3071.7,896.9,1139.2,4142.5
13,2007,10425.5,4158.4,12152.9,5935.6,5166.9,10292.2,4080.3,6126.3,12878.7,...,4770.7,10562.1,2847.5,5077.4,344.1,5681.8,2675.1,720.1,877.6,3500.0
14,2006,8387.0,3538.2,10043.0,4713.6,4161.8,8390.3,3226.5,5329.8,10598.9,...,3900.3,8494.7,2264.1,4090.7,285.9,4595.6,2203.0,585.2,683.3,2957.3
15,2005,7149.8,3158.6,8773.4,4079.4,3523.7,7260.8,2776.5,4756.4,9197.1,...,3448.4,7195.9,1939.9,3497.7,243.1,3817.2,1864.6,499.4,579.9,2520.5
16,2004,6252.5,2621.1,7588.6,3496.0,2942.4,6469.8,2455.2,4134.7,8101.6,...,3059.5,6304.0,1649.4,3136.4,217.9,3141.6,1653.6,443.7,519.9,2170.4
17,2003,5267.2,2257.8,6333.6,2854.3,2388.4,5906.3,2141.0,3609.7,6804.0,...,2615.6,5346.2,1429.0,2633.4,186.0,2587.7,1399.9,385.0,442.6,1889.2
18,2002,4525.7,1926.9,5518.9,2324.8,1940.9,5458.2,2043.1,3242.7,5795.0,...,2279.8,4725.0,1243.4,2358.7,162.0,2253.4,1232.0,340.7,377.2,1612.6
19,2001,3861.5,1756.9,5062.9,2029.5,1713.8,5033.1,1900.9,3043.4,5257.7,...,2014.6,4293.5,1133.3,2159.0,139.2,2010.6,1125.4,300.1,337.4,1491.6
20,2000,3277.8,1591.7,4628.2,1845.7,1539.1,4669.1,1751.4,2855.5,4812.2,...,1822.1,3928.2,1029.9,2030.1,117.8,1804.0,1052.9,263.7,295.0,1363.6
21,1999,2759.8,1435.6,4158.9,1667.1,1379.3,4171.7,1673.0,2536.9,4222.3,...,1687.8,3649.1,937.5,1899.8,106.0,1592.6,956.3,239.4,264.6,1163.2
22,1998,2439.1,1344.7,3924.5,1611.1,1262.5,3881.7,1577.1,2470.2,3831.0,...,1622.4,3474.1,858.4,1831.3,91.5,1458.4,887.7,220.9,245.5,1107.0
23,1997,2118.1,1264.6,3652.1,1476.0,1153.5,3582.5,1464.3,2397.6,3465.3,...,1525.3,3241.5,805.8,1676.2,77.2,1363.6,793.6,202.8,224.6,1039.8
24,1996,1819.4,1121.9,3198.0,1292.1,1023.1,3157.7,1346.8,2137.6,2980.8,...,1326.4,2871.7,723.2,1517.7,65.0,1215.8,722.5,184.2,202.9,900.9
25,1995,1516.2,932.0,2701.2,1076.0,857.1,2793.4,1137.2,1790.2,2518.1,...,1130.6,2443.2,636.2,1222.2,56.1,1036.9,557.8,167.8,175.2,814.9
26,1994,1149.8,732.9,2114.5,826.7,695.1,2461.8,937.7,1448.1,1990.9,...,838.1,2001.4,524.5,983.8,46.0,839.0,453.6,138.4,136.3,662.3
27,1993,888.9,538.9,1620.8,680.4,537.8,2010.8,718.6,1075.3,1519.2,...,611.1,1486.1,417.7,783.3,37.4,678.2,372.2,109.7,104.5,495.3
28,1992,710.2,411.0,1278.5,551.1,421.7,1473.0,558.1,857.4,1114.3,...,462.5,1177.3,339.9,618.7,33.3,531.6,317.8,87.5,83.1,402.3

In [7]:
population_clean = population[~population['Province'].isin(['Servicemen', 'Hainan'])]
population_clean

          Province  Population
0          Beijing    21893095
1          Tianjin    13866009
2            Hebei    74610235
3           Shanxi    34915616
4   Inner Mongolia    24049155
5         Liaoning    42591407
6            Jilin    24073453
7     Heilongjiang    31850088
8         Shanghai    24870895
9          Jiangsu    84748016
10        Zhejiang    64567588
11           Anhui    61027171
12          Fujian    41540086
13         Jiangxi    45188635
14        Shandong   101527453
15           Henan    99365519
16           Hubei    57752557
17           Hunan    66444864
18       Guangdong   126012510
19         Guangxi    50126804
21       Chongqing    32054159
22         Sichuan    83674866
23         Guizhou    38562148
24          Yunnan    47209277
25           Tibet     3648100
26         Shaanxi    39528999
27           Gansu    25019831
28         Qinghai     5923957
29         Ningxia     7202654
30        Xinjiang    25852345

In [8]:
gdp.columns[1:].tolist()

['Beijing',
 'Tianjin',
 'Hebei',
 'Shanxi',
 'Inner Mongolia',
 'Liaoning',
 'Jilin',
 'Heilongjiang',
 'Shanghai',
 'Jiangsu',
 'Zhejiang',
 'Anhui',
 'Fujian',
 'Jiangxi',
 'Shandong',
 'Henan',
 'Hubei',
 'Hunan',
 'Guangdong',
 'Guangxi,',
 'Hainan',
 'Chongqing',
 'Sichuan',
 'Guizhou',
 'Yunnan',
 'Tibet',
 'Shaanxi',
 'Gansu',
 'Qinghai',
 'Ningxia',
 'Xinjiang']

In [9]:
population_clean['Province'].tolist()

['Beijing',
 'Tianjin',
 'Hebei',
 'Shanxi',
 'Inner Mongolia',
 'Liaoning',
 'Jilin',
 'Heilongjiang',
 'Shanghai',
 'Jiangsu',
 'Zhejiang',
 'Anhui',
 'Fujian',
 'Jiangxi',
 'Shandong',
 'Henan',
 'Hubei',
 'Hunan',
 'Guangdong',
 'Guangxi',
 'Chongqing',
 'Sichuan',
 'Guizhou',
 'Yunnan',
 'Tibet',
 'Shaanxi',
 'Gansu',
 'Qinghai',
 'Ningxia',
 'Xinjiang']

In [10]:
set(gdp.columns[1:]).difference(set(population_clean['Province']))

{'Guangxi,', 'Hainan'}

In [11]:
gdp_clean = gdp.rename(columns={'Guangxi,': 'Guangxi'})
gdp_clean = gdp_clean.drop('Hainan', axis=1)
gdp_clean

,Year,Beijing,Tianjin,Hebei,Shanxi,Inner Mongolia,Liaoning,Jilin,Heilongjiang,Shanghai,...,Chongqing,Sichuan,Guizhou,Yunnan,Tibet,Shaanxi,Gansu,Qinghai,Ningxia,Xinjiang
0,2020,36102.6,14083.7,36206.9,17651.9,17359.8,25115.0,12311.3,13698.5,38700.6,...,25002.8,48598.8,17826.6,24521.9,1902.7,26181.9,9016.7,3005.9,3920.6,13797.6
1,2019,35445.1,14055.5,34978.6,16961.6,17212.5,24855.3,11726.8,13544.4,37987.6,...,23605.8,46363.8,16769.3,23223.8,1697.8,25793.2,8718.3,2941.1,3748.5,13597.1
2,2018,33106.0,13362.9,32494.6,15958.1,16140.8,23510.5,11253.8,12846.5,36011.8,...,21588.8,42902.1,15353.2,20880.6,1548.4,23941.9,8104.1,2748.0,3510.2,12809.4
3,2017,29883.0,12450.6,30640.8,14484.3,14898.1,21693.0,10922.0,12313.0,32925.0,...,20066.3,37905.1,13605.4,18486.0,1349.0,21473.5,7336.7,2465.1,3200.3,11159.9
4,2016,27041.2,11477.2,28474.1,11946.4,13789.3,20392.5,10427.0,11895.0,29887.0,...,18023.0,33138.5,11792.4,16369.0,1173.0,19045.8,6907.9,2258.2,2781.4,9630.8
5,2015,24779.1,10879.5,26398.4,11836.4,12949.0,20210.3,10018.0,11690.0,26887.0,...,16040.5,30342.0,10541.0,14960.0,1043.0,17898.8,6556.6,2011.0,2579.4,9306.9
6,2014,22926.0,10640.6,25208.9,12094.7,12158.2,20025.7,9966.5,12170.8,25269.8,...,14623.8,28891.3,9173.1,14041.7,939.7,17402.5,6518.4,1847.7,2473.9,9264.5
7,2013,21134.6,9945.4,24259.6,11987.2,11392.4,19208.8,9427.9,11849.1,23204.1,...,13027.6,26518.0,7973.1,12825.5,828.2,15905.4,6014.5,1713.3,2327.7,8392.6
8,2012,19024.7,9043.0,23077.5,11683.1,10470.1,17848.6,8678.0,11015.8,21305.6,...,11595.4,23922.4,6742.2,11097.4,710.2,14142.4,5393.1,1528.5,2131.0,7411.8
9,2011,17188.8,8112.5,21384.7,10894.4,9458.1,16354.9,7734.6,9935.0,20009.7,...,10161.2,21050.9,5615.6,9523.1,611.5,12175.1,4816.9,1370.4,1931.8,6532.0
10,2010,14964.0,6830.8,18003.6,8903.9,8199.9,13896.3,6410.5,8308.3,17915.4,...,8065.3,17224.8,4519.0,7735.3,512.9,9845.2,3943.7,1144.2,1571.7,5360.2
11,2009,12900.9,5709.6,15306.9,7147.6,7104.2,12815.7,5434.8,7218.9,15742.4,...,6651.2,14190.6,3856.7,6574.4,445.7,7997.8,3268.3,939.7,1266.7,4237.0
12,2008,11813.1,5182.4,14200.1,7223.0,6242.4,12137.7,4834.7,7134.2,14536.9,...,5899.5,12756.2,3504.5,6016.6,398.2,7177.8,3071.7,896.9,1139.2,4142.5
13,2007,10425.5,4158.4,12152.9,5935.6,5166.9,10292.2,4080.3,6126.3,12878.7,...,4770.7,10562.1,2847.5,5077.4,344.1,5681.8,2675.1,720.1,877.6,3500.0
14,2006,8387.0,3538.2,10043.0,4713.6,4161.8,8390.3,3226.5,5329.8,10598.9,...,3900.3,8494.7,2264.1,4090.7,285.9,4595.6,2203.0,585.2,683.3,2957.3
15,2005,7149.8,3158.6,8773.4,4079.4,3523.7,7260.8,2776.5,4756.4,9197.1,...,3448.4,7195.9,1939.9,3497.7,243.1,3817.2,1864.6,499.4,579.9,2520.5
16,2004,6252.5,2621.1,7588.6,3496.0,2942.4,6469.8,2455.2,4134.7,8101.6,...,3059.5,6304.0,1649.4,3136.4,217.9,3141.6,1653.6,443.7,519.9,2170.4
17,2003,5267.2,2257.8,6333.6,2854.3,2388.4,5906.3,2141.0,3609.7,6804.0,...,2615.6,5346.2,1429.0,2633.4,186.0,2587.7,1399.9,385.0,442.6,1889.2
18,2002,4525.7,1926.9,5518.9,2324.8,1940.9,5458.2,2043.1,3242.7,5795.0,...,2279.8,4725.0,1243.4,2358.7,162.0,2253.4,1232.0,340.7,377.2,1612.6
19,2001,3861.5,1756.9,5062.9,2029.5,1713.8,5033.1,1900.9,3043.4,5257.7,...,2014.6,4293.5,1133.3,2159.0,139.2,2010.6,1125.4,300.1,337.4,1491.6
20,2000,3277.8,1591.7,4628.2,1845.7,1539.1,4669.1,1751.4,2855.5,4812.2,...,1822.1,3928.2,1029.9,2030.1,117.8,1804.0,1052.9,263.7,295.0,1363.6
21,1999,2759.8,1435.6,4158.9,1667.1,1379.3,4171.7,1673.0,2536.9,4222.3,...,1687.8,3649.1,937.5,1899.8,106.0,1592.6,956.3,239.4,264.6,1163.2
22,1998,2439.1,1344.7,3924.5,1611.1,1262.5,3881.7,1577.1,2470.2,3831.0,...,1622.4,3474.1,858.4,1831.3,91.5,1458.4,887.7,220.9,245.5,1107.0
23,1997,2118.1,1264.6,3652.1,1476.0,1153.5,3582.5,1464.3,2397.6,3465.3,...,1525.3,3241.5,805.8,1676.2,77.2,1363.6,793.6,202.8,224.6,1039.8
24,1996,1819.4,1121.9,3198.0,1292.1,1023.1,3157.7,1346.8,2137.6,2980.8,...,1326.4,2871.7,723.2,1517.7,65.0,1215.8,722.5,184.2,202.9,900.9
25,1995,1516.2,932.0,2701.2,1076.0,857.1,2793.4,1137.2,1790.2,2518.1,...,1130.6,2443.2,636.2,1222.2,56.1,1036.9,557.8,167.8,175.2,814.9
26,1994,1149.8,732.9,2114.5,826.7,695.1,2461.8,937.7,1448.1,1990.9,...,838.1,2001.4,524.5,983.8,46.0,839.0,453.6,138.4,136.3,662.3
27,1993,888.9,538.9,1620.8,680.4,537.8,2010.8,718.6,1075.3,1519.2,...,611.1,1486.1,417.7,783.3,37.4,678.2,372.2,109.7,104.5,495.3
28,1992,710.2,411.0,1278.5,551.1,421.7,1473.0,558.1,857.4,1114.3,...,462.5,1177.3,339.9,618.7,33.3,531.6,317.8,87.5,83.1,402.3

In [12]:
set(gdp_clean.columns[1:]).difference(set(population_clean['Province']))

set()

In [13]:
set(population_clean['Province']).difference(set(gdp_clean.columns[1:]))

set()

In [14]:
population_clean

          Province  Population
0          Beijing    21893095
1          Tianjin    13866009
2            Hebei    74610235
3           Shanxi    34915616
4   Inner Mongolia    24049155
5         Liaoning    42591407
6            Jilin    24073453
7     Heilongjiang    31850088
8         Shanghai    24870895
9          Jiangsu    84748016
10        Zhejiang    64567588
11           Anhui    61027171
12          Fujian    41540086
13         Jiangxi    45188635
14        Shandong   101527453
15           Henan    99365519
16           Hubei    57752557
17           Hunan    66444864
18       Guangdong   126012510
19         Guangxi    50126804
21       Chongqing    32054159
22         Sichuan    83674866
23         Guizhou    38562148
24          Yunnan    47209277
25           Tibet     3648100
26         Shaanxi    39528999
27           Gansu    25019831
28         Qinghai     5923957
29         Ningxia     7202654
30        Xinjiang    25852345

In [15]:
population_clean.to_csv(clean_data_dir + 'population.csv', index=False)

In [16]:
gdp_final = gdp_clean[gdp_clean['Year'] == 2019]
gdp_final = gdp_final.drop('Year', axis=1)
gdp_final = gdp_final.T.reset_index()
gdp_final = gdp_final.rename(columns={'index': 'Province', 1: 'GDP'})
gdp_final

          Province       GDP
0          Beijing   35445.1
1          Tianjin   14055.5
2            Hebei   34978.6
3           Shanxi   16961.6
4   Inner Mongolia   17212.5
5         Liaoning   24855.3
6            Jilin   11726.8
7     Heilongjiang   13544.4
8         Shanghai   37987.6
9          Jiangsu   98656.8
10        Zhejiang   62462.0
11           Anhui   36845.5
12          Fujian   42326.6
13         Jiangxi   24667.3
14        Shandong   70540.5
15           Henan   53717.8
16           Hubei   45429.0
17           Hunan   39894.1
18       Guangdong  107986.9
19         Guangxi   21237.1
20       Chongqing   23605.8
21         Sichuan   46363.8
22         Guizhou   16769.3
23          Yunnan   23223.8
24           Tibet    1697.8
25         Shaanxi   25793.2
26           Gansu    8718.3
27         Qinghai    2941.1
28         Ningxia    3748.5
29        Xinjiang   13597.1

In [17]:
gdp_final.to_csv(clean_data_dir + 'gdp_2019.csv', index=False)

# Starbucks

In [60]:
starbucks

,city,address,postalCode,latitude,longitude,features,hasArtwork,storeName,storeNumber,closeTime,openTime
0,兰州市,兰州新区出发安检内CF-37商铺中川机场T2航站楼,730000.0,36.504707,103.618088,['OG'],False,兰州中川机场店,52438-281554,21:30:00,06:00:00
1,兰州市,兰州市城关区雁滩路3113号,730000.0,36.061108,103.870931,"['OG', 'DL', 'PO']",False,兰州市欣大百货店,56295-290190,23:00:00,07:30:00
2,兰州市,城关区万达广场1层天水北路68号,730000.0,36.063614,103.862203,"['OG', 'DL', 'MIC', 'PO']",False,兰州城关万达店,24777-238531,23:00:00,07:30:00
3,兰州市,城关区北京华联一层南昌路892号,730000.0,36.055590,103.845779,"['OG', 'DL']",False,兰州平凉路BHG店,52779-282484,23:00:00,07:30:00
4,兰州市,城关区国芳百货1F东方红广场,730000.0,36.051879,103.844903,"['OG', 'DL', 'MIC']",False,兰州东方红国芳百货店,25923-241626,23:00:00,07:30:00
...,...,...,...,...,...,...,...,...,...,...,...
4161,赣州市,赣州市章江新区新赣州大道8号L160铺,341000.0,25.814302,114.926788,"['OG', 'DL', 'MIC', 'PO']",False,赣州万象城店,57342-291456,22:00:00,09:00:00
4162,聊城市,聊城市东昌府区柳园北路长途汽车总站北侧,252000.0,36.478034,115.986818,"['OG', 'DL', 'MIC', 'PO']",False,聊城万达广场店,59913-294209,22:00:00,08:30:00
4163,临汾市,山西省临汾市经济技术开发区汾河路8号None五洲购物广场一层L104号,41000.0,36.102034,111.513453,"['OG', 'MIC', 'PO']",False,临汾五洲国际店,56771-290719,22:00:00,08:30:00
4164,达州市,达州市翠屏街道健身路升华广场1楼1F-9,635000.0,31.185013,107.511220,"['OG', 'MIC', 'PO']",False,达州市升华广场店,59053-292017,22:00:00,07:30:00
4165,重庆市,万州区5幢万达广场2号门北滨大道二段998号,400000.0,30.810148,108.384824,"['OG', 'DL', 'MIC']",False,重庆万州万达广场店,50121-273065,22:30:00,08:00:00

In [67]:
starbucks_clean = starbucks[['city', 'latitude', 'longitude']]
starbucks_clean

     city   latitude   longitude
0     兰州市  36.504707  103.618088
1     兰州市  36.061108  103.870931
2     兰州市  36.063614  103.862203
3     兰州市  36.055590  103.845779
4     兰州市  36.051879  103.844903
...   ...        ...         ...
4161  赣州市  25.814302  114.926788
4162  聊城市  36.478034  115.986818
4163  临汾市  36.102034  111.513453
4164  达州市  31.185013  107.511220
4165  重庆市  30.810148  108.384824

[4166 rows x 3 columns]

In [71]:
starbucks_clean['city'].value_counts().index.tolist()

['上海市',
 '北京市',
 '杭州市',
 '苏州市',
 '广州市',
 '深圳市',
 '成都市',
 '南京市',
 '武汉市',
 '宁波市',
 '天津市',
 '重庆市',
 '西安市',
 '佛山市',
 '无锡市',
 '东莞市',
 '厦门市',
 '青岛市',
 '长沙市',
 '嘉兴市',
 '温州市',
 '常州市',
 '福州市',
 '南通市',
 '沈阳市',
 '绍兴市',
 '大连市',
 '昆明市',
 '郑州市',
 '金华市',
 '济南市',
 '合肥市',
 '扬州市',
 '台州市',
 '泉州市',
 '珠海市',
 '南宁市',
 '哈尔滨',
 '镇江市',
 '湖州市',
 'Shanghai',
 '贵阳',
 '南昌市',
 '泰州市',
 '徐州市',
 '海口市',
 '太原市',
 '中山市',
 '石家庄',
 '江门市',
 '惠州市',
 '长春市',
 '三亚市',
 '盐城市',
 '舟山市',
 '烟台市',
 '汕头市',
 '衢州市',
 '桂林',
 '柳州',
 '兰州市',
 '湛江市',
 '呼和浩特',
 '淮安市',
 '宿迁市',
 '临沂市',
 '保定市',
 '廊坊市',
 '芜湖市',
 '洛阳',
 '连云港市',
 'Hangzhou',
 '宜昌市',
 '淄博市',
 '衡阳市',
 '秦皇岛',
 '唐山市',
 '泸州市',
 '鞍山市',
 'Ningbo',
 '潍坊市',
 '襄阳市',
 '银川市',
 '丽水市',
 '清远市',
 '包头市',
 '漳州市',
 '宜宾市',
 '吉林市',
 '大庆市',
 '阳江市',
 '西宁市',
 '乐山市',
 '宁德市',
 '绵阳市',
 '德阳市',
 '常德市',
 'Suzhou',
 '济宁市',
 '马鞍山',
 '淮南市',
 '九江市',
 '肇庆市',
 '张家口',
 '莆田市',
 '丽江市',
 '邯郸',
 '沧州市',
 '开封市',
 '遵义市',
 '蚌埠市',
 '茂名市',
 '岳阳市',
 '梅州市',
 '眉山市',
 '威海市',
 '荆州市',
 '十堰市',
 '云浮',
 '东营市',
 '汕尾市',
 '德州市',
 '大同市',
 '龙岩市',
 '河源市',
 '丹东市',
 '营口市',
 '锦州',
 '曲靖市',
 '南充市',
 '湘潭市',
 '株洲市',
 '大理市',
 '邢台市',
 '鄂尔多斯市',
 '盘锦市',
 '黄石市',
 '渭南市',
 '咸阳市',
 '宝鸡市',
 '北海市',
 '赣州市',
 '临汾市',
 '承德市',
 '聊城市',
 '长治市',
 '衡水市',
 '运城市',
 '赤峰市',
 '牡丹江市',
 '郴州市',
 '贵港市',
 '日照市',
 '揭阳市',
 '延吉市',
 'Nanjing',
 '安庆市',
 'Anqing',
 '儋州市',
 '三明市',
 '泰安市',
 'Wuhan',
 '韶关市',
 '潮州市',
 'Guangzhou',
 '钦州市',
 '贵阳市',
 '齐齐哈尔市',
 '晋城市',
 '许昌市',
 '荆门市',
 '景洪市',
 '普洱市',
 '西昌市',
 '自贡市',
 '雅安市',
 '晋中市',
 'Wuxi',
 'Nantong',
 '本溪市',
 '辽阳市',
 '抚顺市',
 '达州市']

In [72]:
starbucks_clean.to_csv(clean_data_dir + 'starbucks.csv', index=False)

In [85]:
starbucks_shanghai = starbucks_clean[starbucks_clean['city'].isin(['上海市', 'Shanghai'])].reset_index(drop=True)
starbucks_shanghai['city'] = 'Shanghai'
starbucks_shanghai

         city   latitude   longitude
0    Shanghai  31.620879  121.396525
1    Shanghai  31.397641  121.247911
2    Shanghai  31.390531  121.237405
3    Shanghai  31.402251  121.350569
4    Shanghai  31.384432  121.245575
..        ...        ...         ...
749  Shanghai  30.871616  121.818975
750  Shanghai  30.756536  121.329269
751  Shanghai  30.894577  121.906005
752  Shanghai  30.881270  121.902452
753  Shanghai  30.896360  121.925550

[754 rows x 3 columns]

In [86]:
starbucks_shanghai.to_csv(clean_data_dir + 'starbucks_shanghai.csv', index=False)